//reserved.go

package main

var reservedSubdomains = map[string]bool{
	// Core / site-wide
	"www":     true,
	"api":     true,
	"app":     true,
	"apps":    true,
	"admin":   true,
	"status":  true,
	"blog":    true,
	"docs":    true,
	"help":    true,
	"support": true,
	"about":   true,
	"contact": true,
	"legal":   true,
	"privacy": true,
	"terms":   true,
	"abuse":   true,
	"dmca":    true,

	// Auth / identity / trust
	"auth":         true,
	"login":        true,
	"logout":       true,
	"signup":       true,
	"register":     true,
	"oauth":        true,
	"account":      true,
	"accounts":     true,
	"profile":      true,
	"settings":     true,
	"dashboard":    true,
	"console":      true,
	"billing":      true,
	"payments":     true,
	"checkout":     true,
	"pricing":      true,
	"security":     true,
	"verify":       true,
	"verification": true,
	"confirm":      true,
	"activate":     true,
	"password":     true,
	"reset":        true,
	"mfa":          true,
	"2fa":          true,

	// Official platform features
	"forum":       true,
	"forums":      true,
	"brew":        true,
	"chat":        true,
	"studio":      true,
	"create":      true,
	"editor":      true,
	"edit":        true,
	"publish":     true,
	"upload":      true,
	"uploads":     true,
	"download":    true,
	"downloads":   true,
	"search":      true,
	"browse":      true,
	"explore":     true,
	"discover":    true,
	"catalog":     true,
	"games":       true,
	"game":        true,
	"featured":    true,
	"trending":    true,
	"new":         true,
	"random":      true,
	"feed":        true,
	"rss":         true,
	"tag":         true,
	"tags":        true,
	"genre":       true,
	"genres":      true,
	"library":     true,
	"collections": true,

	// Community / social
	"user":          true,
	"users":         true,
	"creator":       true,
	"creators":      true,
	"community":     true,
	"staff":         true,
	"team":          true,
	"mod":           true,
	"moderator":     true,
	"official":      true,
	"system":        true,
	"me":            true,
	"inbox":         true,
	"message":       true,
	"messages":      true,
	"comment":       true,
	"comments":      true,
	"notifications": true,
	"notify":        true,

	// Assets / infra
	"cdn":     true,
	"static":  true,
	"assets":  true,
	"asset":   true,
	"img":     true,
	"image":   true,
	"images":  true,
	"media":   true,
	"file":    true,
	"files":   true,
	"storage": true,
	"backup":  true,

	// Email / network / infra-sensitive
	"mail":  true,
	"smtp":  true,
	"imap":  true,
	"pop":   true,
	"pop3":  true,
	"ftp":   true,
	"sftp":  true,
	"ssh":   true,
	"ns":    true,
	"ns1":   true,
	"ns2":   true,
	"ns3":   true,
	"ns4":   true,
	"mx":    true,
	"proxy": true,
	"vpn":   true,

	// Dev / staging / internal
	"dev":       true,
	"test":      true,
	"beta":      true,
	"alpha":     true,
	"staging":   true,
	"preview":   true,
	"canary":    true,
	"sandbox":   true,
	"demo":      true,
	"localhost": true,
	"local":     true,
	"internal":  true,
	"intranet":  true,

	// Brand / anti-confusion
	"cyoa":   true,
	"cafe":   true,
	"host":   true,
	"server": true,
	"root":   true,

	// Theme / cafe flavor / future branding
	"treat":  true,
	"treats": true,
	"serve":  true,
	"menu":   true,
	"bite":   true,
	"cup":    true,
	"table":  true,
	"room":   true,
	"booth":  true,
	"dream":  true,
	"dreams": true,
}
